name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ewan-pugh
        password: ${{ secrets.CR_PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/LU-Centre-for-Autonomous-Systems/px4-gazebo-ros:latest
        docker push ghcr.io/ewan-pugh/px4-gazebo-ros:latest

